# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
 secret_key_base: 1951b86b5aadd77c942a1550e92dc73d27bc6089cdb2bd93deca991a52b1bf630495a12521c6aab1045aa15095900979f0c72f52a4deadd5aeebab554d0047f8

 action_mailer:
  default_url_options:
   host: "localhost:3000"
  delivery_method: "smtp"


  smtp_settings:
   address: "smtp.gmail.com"
   domain: "gmail.com"
   port: "587"
   user_name: "moja.strona.2016@gmail.com"
   password: "Qazwsxedc1"
   authentcations: :plain
   enable_starttls_auto: "true"

test:
 secret_key_base: 87dfa7eb447a450a87a0f3112affc441cf1b919f1598ad3dfc28b7f461ccf62a7c065989ad5ceb9e7c934c88fd0e8c0ef6272c48b0e4e73434c48cf510576929

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
